### ISSUE TITLE
Error: Cannot find module 'espree' after upgrading to 2.0.0

### ISSUE THREAD

**Issue by pinalbhatt** [adametry/gulp-eslint#138]
Getting following error after upgrading to 2.0.0

/usr/local/bin/node /usr/local/lib/node_modules/gulp/bin/gulp.js --color --gulpfile myproject/gulpfile.js esLint-ServerJS
myproject/node_modules/gulp-print/node_modules/map-stream/index.js:103
        throw err
        ^

Error: Cannot find module 'espree' from 'myproject/node_modules/gulp-eslint/node_modules'
    at Function.module.exports [as sync] (myproject/node_modules/gulp-eslint/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at Object.load (myproject/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:446:43)
    at loadConfig (myproject/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (myproject/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (myproject/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:222:22)
[    at processText (myproject/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:155:27)
    at CLIEngine.executeOnText (myproject/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:671:26)
    at verify (myproject/node_modules/gulp-eslint/index.js:20:23)
    at Transform._transform (myproject/node_modules/gulp-eslint/index.js:68:18)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)

**Comment by shinnn** [comment]
That has nothing to do with this plugin. Probably an issue with one of the upstream projects.
